apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: firstapp
  name: firstapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: firstapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: firstapp
    spec:
      containers:
      - image: ssankar08d/firstapp:9f0d168ec407bfa3874824cb7c9340e603c7b8c0
        name: firstapp
        resources: {}
status: {}