apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: firstapp
  name: firstapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: firstapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: firstapp
    spec:
      containers:
      - image: sankar08d/firstapp:2.0
        name: firstapp
        resources: {}
status: {}