name : Continous implementation of First Web App

# This is CI just has Docker Login, Building and Pushing the image only 

on: 
  push:
    branches:
      - main
  workflow_dispatch:
    
jobs:
    docker_build_push:
        name: docker build and pushing
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v4

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ vars.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                push: false
                context: .
                tags: ${{ vars.DOCKERHUB_USERNAME }}/firstapp:${{ github.sha }} 

            - name: Checking image
              run: |
                docker images
                docker run -p 3000:3000 ${{ vars.DOCKERHUB_USERNAME }}/firstapp:${{ github.sha }} 
                curl https://localhost:3000